import Image from "next/image";
import Link from "next/link";

const references = ["/images/stitch/d0451af950.jpg", "/images/stitch/0a3126559e.jpg", "/images/stitch/92121f0ce3.jpg", "/images/stitch/87e8f763c6.jpg"];
const fields = ["Diámetro nominal", "Longitud", "Clase de presión", "Unión"];
const groups = ["Recubrimiento", "Revestimiento", "Unión y accesorios"];

export function ScreenW04() {
  return (
    <main className="min-h-screen w-full bg-background pt-[76px] text-on-surface">
      <section className="bg-surface-container-low py-8 px-4 sm:py-10 sm:px-6"><div className="mx-auto max-w-[1200px] space-y-6">
        <nav aria-label="Migas de pan" className="font-ui-label text-ui-label text-text-muted"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Inicio</Link></li><li aria-hidden="true">/</li><li><Link href="/productos">Productos</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="font-semibold text-on-surface">Tuberías</li></ol></nav>
        <div className="max-w-4xl"><span className="inline-flex items-center gap-2 rounded-lg bg-surface-container px-3 py-1 font-ui-label text-ui-label font-semibold tracking-wide text-primary"><span aria-hidden="true" className="material-symbols-outlined text-[16px]">info</span>Información técnica pendiente de validación</span><h1 className="mt-3 font-headline-hero text-[clamp(2.25rem,5vw,3.5rem)] font-semibold leading-[1.05] tracking-tight">Tuberías de hierro dúctil</h1><p className="mt-4 max-w-3xl font-body-default text-body-default leading-relaxed text-text-secondary">Consulta la información disponible para esta familia y comparte los requisitos de tu proyecto con el equipo.</p><Link href="/cotizar" className="mt-6 inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-primary px-6 font-button-text text-button-text font-semibold text-on-primary shadow-sm hover:bg-primary-container focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus">Solicitar cotización<span aria-hidden="true" className="material-symbols-outlined text-[18px]">arrow_forward</span></Link></div>
        <div className="grid grid-cols-2 gap-3 pt-2 md:grid-cols-4">{fields.map((label) => <article key={label} className="min-h-[112px] rounded-xl bg-surface-container-lowest p-4 shadow-sm sm:p-5"><div className="flex items-center gap-2 text-primary"><span aria-hidden="true" className="material-symbols-outlined text-[20px]">info</span><span className="font-ui-label text-ui-label font-semibold uppercase text-text-muted">{label}</span></div><p className="mt-2 font-headline-card text-headline-card font-semibold text-on-surface">Pendiente</p><p className="font-ui-label text-ui-label text-text-muted">Por validar</p></article>)}</div>
      </div></section>

      <section aria-labelledby="families-title" className="bg-surface py-12 px-4 sm:py-16 sm:px-6"><div className="mx-auto max-w-[1200px]"><div className="mb-7"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-[.12em] text-primary">Información de producto</p><h2 id="families-title" className="mt-1 font-headline-section text-headline-section">Datos técnicos pendientes</h2></div><div className="grid gap-5 md:grid-cols-3">{groups.map((title, i) => <article key={title} className="rounded-xl border border-border bg-surface-container-lowest p-5 sm:p-6"><span aria-hidden="true" className="material-symbols-outlined grid size-11 place-items-center rounded-lg bg-surface-container text-[22px] text-primary">{["layers", "texture", "settings_input_component"][i]}</span><h3 className="mt-4 font-headline-card text-headline-card font-semibold">{title}</h3><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">Información pendiente de validación.</p><div className="mt-4 rounded-lg bg-surface p-3 font-ui-label text-ui-label text-text-muted">Documentación técnica pendiente</div><dl className="mt-3 divide-y divide-border font-ui-label text-ui-label">{["Material", "Revestimiento", "Uso previsto", "Documento técnico"].map((label) => <div key={label} className="flex min-h-9 items-center justify-between gap-2 py-1"><dt className="text-text-muted">{label}</dt><dd className="m-0 text-right font-semibold text-text-secondary">Pendiente</dd></div>)}</dl></article>)}</div></div></section>

      <section aria-labelledby="products-title" className="bg-surface-container-lowest py-12 px-4 sm:py-16 sm:px-6"><div className="mx-auto max-w-[1200px]"><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p className="font-ui-label text-ui-label font-semibold uppercase tracking-[.12em] text-primary">Catálogo</p><h2 id="products-title" className="mt-1 font-headline-section text-headline-section">Referencias visuales</h2></div><p className="font-ui-label text-ui-label text-text-muted">Datos de producto pendientes de validación</p></div><div className="grid gap-5 md:grid-cols-2">{references.map((src, i) => <article key={src} className="flex flex-col overflow-hidden rounded-xl border border-border bg-surface shadow-sm"><div className="relative aspect-[16/9] bg-surface-container"><Image src={src} alt="Imagen referencial de una tubería industrial." width={1408} height={768} sizes="(min-width: 768px) 50vw, 100vw" className="h-full w-full object-cover" /><span className="absolute left-3 top-3 rounded bg-surface-container-lowest/95 px-2.5 py-1 font-ui-label text-ui-label text-text-secondary">Imagen referencial</span></div><div className="flex flex-1 flex-col p-5"><h3 className="font-headline-card text-headline-card font-semibold">Referencia visual {String(i + 1).padStart(2, "0")}</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Identificación y características pendientes de validación.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-surface-container-low p-3 font-ui-label text-ui-label"><p className="text-text-muted">Especificaciones</p><p className="mt-1 font-semibold text-text-secondary">Pendientes de validación</p></div><div className="rounded-lg bg-surface-container-low p-3 font-ui-label text-ui-label"><p className="text-text-muted">Disponibilidad</p><p className="mt-1 font-semibold text-text-secondary">Pendiente de confirmación</p></div></div><dl className="mt-3 grid gap-x-5 divide-y divide-border rounded-lg bg-surface p-3 font-ui-label text-ui-label sm:grid-cols-2">{[...fields, "Documento técnico", "Identificación comercial"].map((label) => <div key={label} className="flex min-h-9 items-center justify-between gap-2 py-1"><dt className="text-text-muted">{label}</dt><dd className="m-0 text-right font-semibold text-text-secondary">Pendiente</dd></div>)}</dl><Link href="/cotizar" className="mt-4 inline-flex min-h-11 items-center justify-center rounded-lg bg-primary px-4 font-button-text text-button-text font-semibold text-on-primary hover:bg-primary-container">Consultar</Link></div></article>)}</div></div></section>

            <section aria-labelledby="installation-title" className="bg-surface-container-low py-12 px-4 sm:py-16 sm:px-6"><div className="mx-auto max-w-[1200px]"><div className="mb-6"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-[.12em] text-primary">Guía de referencia</p><h2 id="installation-title" className="mt-1 font-headline-section text-headline-section">Instalación y soporte</h2></div><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-xl border border-border bg-surface-container-lowest p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-3">{["Preparación", "Montaje", "Inspección"].map((label, i) => <div key={label} className="rounded-lg bg-surface-container-low p-4"><span className="grid size-9 place-items-center rounded-full bg-primary text-sm font-bold text-on-primary">{i + 1}</span><h3 className="mt-3 font-headline-card text-headline-card font-semibold">{label}</h3><p className="mt-2 font-ui-label text-ui-label leading-relaxed text-text-muted">Procedimiento pendiente de documentación.</p></div>)}</div><div className="mt-5 overflow-x-auto rounded-lg border border-border" role="region" aria-label="Tabla de instalación pendiente de validación" tabIndex={0}><table className="w-full min-w-[680px] border-collapse text-left font-ui-label text-ui-label"><thead className="bg-surface-container"><tr>{["Etapa", "Documento aplicable", "Responsable técnico", "Estado"].map((label) => <th key={label} scope="col" className="px-4 py-3 font-semibold text-on-surface">{label}</th>)}</tr></thead><tbody>{["Limpieza y alojamiento", "Lubricación", "Inserción y enchufado", "Deflexión de junta", "Inspección final"].map((label) => <tr key={label} className="border-t border-border"><th scope="row" className="px-4 py-3 font-medium text-on-surface">{label}</th><td className="px-4 py-3 text-text-muted">Pendiente de aprobación</td><td className="px-4 py-3 text-text-muted">Por confirmar</td><td className="px-4 py-3 font-semibold text-text-muted">No publicado</td></tr>)}</tbody></table></div><div className="mt-4 rounded-lg border border-border bg-surface p-4 font-body-compact text-body-compact text-text-secondary">Instrucciones de montaje y criterios técnicos pendientes de aprobación.</div></div><aside className="flex flex-col justify-between gap-5 rounded-xl bg-primary-container p-6 text-on-primary sm:p-8"><div><span aria-hidden="true" className="material-symbols-outlined text-[26px]">engineering</span><h3 className="mt-3 font-headline-card text-headline-card font-bold">Consulta al equipo</h3><p className="mt-2 font-body-compact text-body-compact">Indica el proyecto y la familia de producto para solicitar información.</p></div><Link href="/cotizar" className="inline-flex min-h-11 items-center justify-center rounded-lg bg-surface-container-lowest px-5 font-button-text text-button-text font-semibold text-primary">Solicitar cotización</Link></aside></div></div></section>
      <section aria-labelledby="quote-title" className="bg-surface py-12 px-4 sm:py-16 sm:px-6"><div className="mx-auto max-w-[1200px]"><div className="mb-6"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-[.12em] text-primary">Consulta técnica</p><h2 id="quote-title" className="mt-1 font-headline-section text-headline-section font-bold">Comparte el requerimiento de tu proyecto</h2><p className="mt-2 max-w-3xl font-body-default text-body-default text-text-secondary">Los documentos, configuraciones y condiciones de suministro se confirmarán cuando se valide la información de esta familia.</p></div><div className="grid gap-5 md:grid-cols-3">{["Producto requerido", "Condiciones del proyecto", "Documentación aplicable"].map((label) => <div key={label} className="rounded-xl border border-border bg-surface-container-lowest p-5"><h3 className="font-headline-card text-headline-card font-semibold">{label}</h3><p className="mt-3 min-h-12 rounded-lg bg-surface p-3 font-body-compact text-body-compact text-text-muted">Pendiente de validación</p></div>)}</div><div className="mt-5 flex flex-col gap-4 rounded-xl bg-primary-container p-6 text-on-primary sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><h3 className="font-headline-card text-headline-card font-bold">Solicitar información</h3><p className="mt-2 max-w-2xl font-body-compact text-body-compact">Indica la familia y los requisitos en el formulario de cotización.</p></div><Link href="/cotizar" className="inline-flex min-h-11 shrink-0 items-center justify-center rounded-lg bg-surface-container-lowest px-5 font-button-text text-button-text font-semibold text-primary">Ir a cotizar</Link></div></div></section>
    </main>
  );
}
