import Image from "next/image";
import Link from "next/link";
import { W08Gallery } from "@/screens/islands/w08-gallery";

const fields = ["Diámetro y dimensiones", "Clase de producto", "Tipo de unión", "Revestimiento", "Condiciones de operación", "Documentación"];
const details = ["Materiales", "Unión y accesorios", "Instalación", "Mantenimiento"];

export function ScreenW08() {
  return (
    <main className="min-h-screen bg-background pt-[76px] text-on-surface">
      <div className="mx-auto max-w-[1200px] px-4 pt-6 sm:px-6 sm:pt-8 lg:px-8">
        <nav aria-label="Ruta de navegación" className="mb-7 font-ui-label text-ui-label text-text-muted"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Inicio</Link></li><li aria-hidden="true">/</li><li><Link href="/productos">Productos</Link></li><li aria-hidden="true">/</li><li><Link href="/productos/tuberias">Tuberías</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="font-semibold text-on-surface">Ficha de producto</li></ol></nav>
        <section aria-labelledby="product-title" className="grid items-start gap-8 pb-12 lg:grid-cols-12 lg:gap-8 lg:pb-16">
          <div className="space-y-3 lg:col-span-7"><W08Gallery><span className="absolute left-4 top-4 z-10 rounded bg-surface-elevated/95 px-2.5 py-1 font-ui-label text-ui-label font-semibold text-on-surface">Imagen referencial</span><span className="absolute bottom-4 left-4 z-10 rounded bg-surface-elevated/95 px-2.5 py-1 font-ui-label text-ui-label text-text-muted">Información técnica pendiente</span></W08Gallery><p className="rounded-lg border border-border bg-surface-container-low px-4 py-3 font-ui-label text-ui-label text-text-secondary">Las vistas y esquemas se muestran como referencia visual.</p></div>
          <div className="flex flex-col gap-5 rounded-xl border border-border bg-surface-container-lowest p-5 shadow-sm sm:p-7 lg:col-span-5 lg:p-8">
            <div className="space-y-2"><p className="inline-flex rounded bg-surface-container px-2.5 py-1 font-ui-label text-ui-label font-semibold uppercase tracking-[.1em] text-primary">Ficha de producto · Información pendiente</p><h1 id="product-title" className="font-headline-section text-headline-section font-bold leading-tight tracking-tight">Tubería de hierro dúctil</h1><p className="font-body-default text-body-default leading-relaxed text-text-secondary">Consulta esta opción para tu proyecto. El equipo confirmará los datos y documentación correspondientes.</p></div>
            <dl className="divide-y divide-border rounded-lg bg-surface p-4">{fields.slice(0, 4).map((label) => <div key={label} className="flex min-h-11 items-center justify-between gap-3 py-2"><dt className="font-body-compact text-body-compact text-text-secondary">{label}</dt><dd className="m-0 text-right font-ui-label text-ui-label font-medium text-text-muted">Pendiente de validación</dd></div>)}</dl>
            <Link href="/cotizar" className="inline-flex min-h-12 items-center justify-center rounded-lg bg-primary px-6 font-button-text text-button-text font-semibold text-on-primary shadow-sm transition-colors hover:bg-primary-container focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus motion-reduce:transition-none">Solicitar cotización</Link>
            <p className="font-ui-label text-ui-label text-text-muted">Información técnica pendiente de validación.</p>
          </div>
        </section>
      </div>
      <section aria-labelledby="technical-title" className="bg-surface-container-low py-12 sm:py-16"><div className="mx-auto max-w-[1200px] px-4 sm:px-6 lg:px-8"><div className="mb-6"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-[.12em] text-primary">Ficha de producto</p><h2 id="technical-title" className="mt-1 font-headline-section text-headline-section font-bold">Información técnica</h2></div><div className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><div className="space-y-3">{details.map((label, i) => <div key={label} className="flex min-h-20 items-center gap-4 rounded-xl border border-border bg-surface-container-lowest p-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-surface-container font-headline-card text-headline-card font-semibold text-primary">{i + 1}</span><div><h3 className="font-headline-card text-headline-card font-semibold">{label}</h3><p className="mt-1 font-ui-label text-ui-label text-text-muted">Pendiente de validación</p></div></div>)}</div><div className="grid gap-3 rounded-xl border border-border bg-surface-container-lowest p-4 sm:grid-cols-2 sm:p-5">{fields.map((label) => <div key={label} className="flex min-h-16 items-center justify-between gap-3 rounded-lg bg-surface p-4"><span className="font-body-compact text-body-compact text-text-secondary">{label}</span><span className="text-right font-ui-label text-ui-label font-semibold text-text-muted">Pendiente de validación</span></div>)}</div></div></div></section>
      <section aria-labelledby="coatings-title" className="bg-surface-container-low py-12 sm:py-16"><div className="mx-auto max-w-[1200px] px-4 sm:px-6 lg:px-8"><div className="mb-6 text-center"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-[.12em] text-primary">Protección de superficies</p><h2 id="coatings-title" className="mt-1 font-headline-section text-headline-section font-bold">Revestimientos interior y exterior</h2><p className="mx-auto mt-2 max-w-3xl font-body-default text-body-default text-text-secondary">Los materiales, espesores y métodos de aplicación requieren validación documental.</p></div><div className="grid gap-5 md:grid-cols-2">{["Revestimiento interior", "Revestimiento exterior"].map((title, index) => <article key={title} className="rounded-xl border border-border bg-surface-container-lowest p-5 sm:p-7"><div className="flex items-start gap-4"><span aria-hidden="true" className="material-symbols-outlined grid size-12 shrink-0 place-items-center rounded-lg bg-surface-container text-[24px] text-primary">{index === 0 ? "water_drop" : "shield"}</span><div><p className="font-ui-label text-ui-label font-semibold uppercase tracking-[.1em] text-text-muted">Información por confirmar</p><h3 className="mt-1 font-headline-card text-headline-card font-semibold">{title}</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Documentación de composición y desempeño no publicada.</p></div></div><dl className="mt-5 grid gap-x-6 divide-y divide-border font-ui-label text-ui-label sm:grid-cols-2">{["Material", "Espesor", "Método de aplicación", "Compatibilidad", "Control de calidad", "Documento de referencia"].map((label) => <div key={label} className="flex min-h-11 items-center justify-between gap-2 py-2"><dt className="text-text-muted">{label}</dt><dd className="m-0 text-right font-semibold text-text-secondary">Pendiente de validación</dd></div>)}</dl><p className="mt-4 rounded-lg bg-surface-container-low p-3 font-ui-label text-ui-label text-text-muted">Revestimiento sujeto a aprobación técnica.</p></article>)}</div></div></section>
      <section aria-labelledby="data-title" className="py-12 sm:py-16"><div className="mx-auto max-w-[1200px] px-4 sm:px-6 lg:px-8"><div className="mb-6"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-[.12em] text-primary">Detalle técnico</p><h2 id="data-title" className="mt-1 font-headline-section text-headline-section font-bold">Parámetros de consulta</h2><p className="mt-2 max-w-3xl font-body-default text-body-default text-text-secondary">No hay valores aprobados para publicar en esta ficha.</p></div><div className="overflow-hidden rounded-xl border border-border bg-surface-container-lowest"><div className="grid grid-cols-2 bg-surface-container-low px-4 py-3 font-ui-label text-ui-label font-semibold text-on-surface sm:grid-cols-4">{["Parámetro", "Valor y unidad", "Documento", "Estado"].map((label) => <span key={label}>{label}</span>)}</div>{["Diámetro nominal", "Diámetro exterior", "Tolerancia dimensional", "Espesor de pared", "Presión de operación", "Presión admisible", "Deflexión de unión", "Radio de curvatura", "Peso por longitud", "Material", "Revestimiento", "Trazabilidad"].map((label) => <div key={label} className="grid min-h-14 grid-cols-2 items-center gap-2 border-t border-border px-4 py-3 sm:grid-cols-4"><span className="font-body-compact text-body-compact text-on-surface">{label}</span><span className="font-ui-label text-ui-label text-text-muted">Pendiente de validar</span><span className="font-ui-label text-ui-label text-text-muted">Por confirmar</span><span className="font-ui-label text-ui-label font-semibold text-text-muted">No publicado</span></div>)}</div></div></section>
      <section aria-labelledby="accessories-title" className="py-12 sm:py-16"><div className="mx-auto max-w-[1200px] px-4 sm:px-6 lg:px-8"><h2 id="accessories-title" className="mb-6 font-headline-section text-headline-section font-bold">Accesorios compatibles</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{["Codos y derivaciones", "Reducciones", "Tes", "Insumos de montaje"].map((label, index) => <article key={label} className="overflow-hidden rounded-xl border border-border bg-surface-container-lowest"><div className="relative aspect-[4/3] bg-surface-container"><Image src={["/images/stitch/9455f79b80.jpg", "/images/stitch/d0fa5bbbb8.jpg", "/images/stitch/226cf44fc1.jpg", "/images/stitch/b13009eb5e.jpg"][index]} alt="Imagen referencial de una tubería industrial." width={1408} height={768} sizes="(min-width: 768px) 33vw, 100vw" className="h-full w-full object-cover" /><span className="absolute bottom-3 left-3 rounded bg-surface-container-lowest/95 px-2.5 py-1 font-ui-label text-ui-label text-text-secondary">Imagen referencial</span></div><div className="p-4"><h3 className="font-headline-card text-headline-card font-semibold">{label}</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Información técnica pendiente de validación.</p></div></article>)}</div></div></section>
      
      <section aria-labelledby="quote-title" className="bg-primary-container py-12 sm:py-14"><div className="mx-auto max-w-[1200px] px-4 text-on-primary sm:px-6 lg:px-8"><div className="mb-6"><span aria-hidden="true" className="material-symbols-outlined text-[26px]">request_quote</span><h2 id="quote-title" className="mt-2 font-headline-section text-headline-section font-bold">Consulta un requerimiento</h2><p className="mt-2 max-w-2xl font-body-default text-body-default">La documentación está pendiente de aprobación. Comparte tu requerimiento para consultar al equipo.</p></div><div className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><aside className="rounded-xl bg-surface-container-lowest/10 p-5"><h3 className="font-headline-card text-headline-card font-bold">Información por confirmar</h3><div className="mt-4 space-y-3">{["Especificaciones", "Disponibilidad", "Documentación"].map((label) => <div key={label} className="flex min-h-11 items-center justify-between rounded-lg bg-surface-container-lowest/10 px-3"><span className="font-body-compact text-body-compact">{label}</span><span className="font-ui-label text-ui-label">Pendiente</span></div>)}</div></aside><div className="rounded-xl bg-surface-container-lowest p-5 text-on-surface sm:p-7"><div className="grid gap-4 sm:grid-cols-2">{["Producto", "Cantidad o metrado", "Destino", "Especificaciones del proyecto", "Documentación requerida", "Observaciones"].map((label) => <div key={label} className="min-h-[72px] rounded-lg border border-border bg-surface p-3"><p className="font-ui-label text-ui-label text-text-muted">{label}</p><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Completa en el formulario oficial</p></div>)}</div><Link href="/cotizar" className="mt-5 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-primary px-6 font-button-text text-button-text font-semibold text-on-primary">Abrir formulario de cotización</Link></div></div></div></section>
    </main>
  );
}
