import Link from "next/link";
import { ContentScrollProgress } from "@/shared/ui/content-scroll-progress";
import { W19Toc, type TocItem } from "./islands/w19-toc";

const TOC_ITEMS: readonly TocItem[] = [
  { id: "responsable", number: "01", label: "Responsable del tratamiento" },
  { id: "marco-normativo", number: "02", label: "Marco legal" },
  { id: "datos-recopilados", number: "03", label: "Datos personales" },
  { id: "finalidades", number: "04", label: "Finalidades" },
  { id: "transferencia", number: "05", label: "Transferencias" },
  { id: "conservacion", number: "06", label: "Conservación" },
  { id: "derechos-arco", number: "07", label: "Derechos" },
  { id: "seguridad", number: "08", label: "Seguridad" },
  { id: "modificaciones", number: "09", label: "Actualizaciones" },
];

const pending = "Pendiente de validación y aprobación legal.";
const item = "rounded-lg border border-border bg-surface-container-low p-4";

export function ScreenW19() {
  return (
    <main className="min-h-screen bg-background pt-[76px]">
      <div className="sticky top-[76px] z-30 h-1 bg-surface-container"><ContentScrollProgress id="reading-progress" className="h-full w-0 bg-primary-container transition-all duration-150 motion-reduce:transition-none" /></div>
      <section className="bg-surface-container-lowest px-5 py-8 sm:px-6 sm:py-10 lg:py-12"><div className="mx-auto max-w-[1200px]"><nav aria-label="Migas de pan" className="mb-6 flex flex-wrap items-center gap-2 font-ui-label text-ui-label text-text-muted"><Link href="/" className="hover:text-primary">Inicio</Link><span aria-hidden="true">/</span><span>Marco institucional</span><span aria-hidden="true">/</span><span aria-current="page" className="text-on-surface">Privacidad</span></nav>
        <div className="flex flex-col justify-between gap-6 border-b border-border pb-6 lg:flex-row lg:items-end"><div className="max-w-3xl"><div className="flex flex-wrap gap-2"><span className="inline-flex rounded bg-surface-container px-2.5 py-1 font-ui-label text-ui-label font-semibold text-primary">Aviso legal pendiente</span><span className="inline-flex rounded bg-surface px-2.5 py-1 font-ui-label text-ui-label text-text-muted">Responsable y vigencia por confirmar</span></div><h1 className="mt-4 font-headline-hero text-headline-section font-semibold leading-tight tracking-tight text-on-surface lg:text-headline-hero">Política de privacidad y tratamiento de datos</h1><p className="mt-3 font-body-default text-body-default leading-relaxed text-text-secondary">Esta página conserva la estructura de la política institucional. El texto legal solo se publicará después de revisar el tratamiento de datos y los canales aplicables.</p></div><aside className="grid shrink-0 gap-3 rounded-xl border border-border bg-surface p-4 sm:grid-cols-2 lg:min-w-[300px] lg:grid-cols-1"><div className="flex items-center justify-between gap-4"><span className="font-ui-label text-ui-label text-text-muted">VERSIÓN</span><span className="font-ui-label text-ui-label font-semibold text-primary">Pendiente</span></div><div className="flex items-center justify-between gap-4"><span className="font-ui-label text-ui-label text-text-muted">FECHA DE VIGENCIA</span><span className="font-ui-label text-ui-label font-semibold text-on-surface">Pendiente</span></div><div className="flex items-center justify-between gap-4 sm:col-span-2 lg:col-span-1"><span className="font-ui-label text-ui-label text-text-muted">RESPONSABLE</span><span className="font-ui-label text-ui-label font-semibold text-on-surface">Por confirmar</span></div></aside></div>
      </div></section>

      <section className="px-5 py-8 sm:px-6 sm:py-10 lg:px-8 lg:py-12"><div className="mx-auto grid max-w-[1200px] items-start gap-6 lg:grid-cols-12 lg:gap-8"><aside className="space-y-4 lg:sticky lg:top-28 lg:col-span-4"><div className="rounded-xl border border-border bg-surface p-5"><div className="mb-4 flex items-center gap-2"><span aria-hidden="true" className="material-symbols-outlined text-[20px] text-primary">format_list_bulleted</span><h2 className="font-button-text text-button-text font-semibold">Índice de la política</h2></div><W19Toc items={TOC_ITEMS} /></div><div className="rounded-xl border border-border bg-surface-container-low p-5"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-wide text-primary">Canal de privacidad</p><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">Persona responsable y canal de solicitudes: pendiente de confirmación.</p></div></aside>

      <article className="rounded-xl bg-surface p-6 shadow-sm space-y-12 sm:p-10 lg:col-span-8">
        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="responsable"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">01</span><h2 className="font-headline-card text-headline-card font-semibold">Responsable del tratamiento</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Los datos legales de la entidad responsable todavía deben confirmarse antes de publicar esta información.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className={item}><h3 className="font-ui-label text-ui-label font-semibold text-primary">Identidad legal</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Pendiente de validación.</p><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Razón social y datos de registro por confirmar</p></div><div className={item}><h3 className="font-ui-label text-ui-label font-semibold text-primary">Canal de contacto</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Pendiente de confirmación.</p><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Persona responsable por identificar</p></div></div><div className="mt-3 rounded-lg bg-surface-container-low p-4"><p className="font-ui-label text-ui-label font-semibold text-primary">Información del responsable</p><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">Dirección, medios de contacto y alcance del tratamiento deben confirmarse con FUNDIGSAC antes de completar esta sección.</p></div></section>

        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="marco-normativo"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">02</span><h2 className="font-headline-card text-headline-card font-semibold">Marco legal aplicable</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Las referencias normativas y su aplicación a los formularios del sitio se publicarán tras revisión jurídica.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className={item}><h3 className="font-button-text text-button-text font-semibold">Normativa aplicable</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">{pending}</p></div><div className={item}><h3 className="font-button-text text-button-text font-semibold">Alcance del aviso</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">{pending}</p></div></div><div className="mt-3 grid gap-3 sm:grid-cols-3">{["Textos legales", "Responsabilidades", "Aplicación a formularios"].map((label) => <div key={label} className="rounded-lg border border-border bg-surface-container-low p-4"><h3 className="font-ui-label text-ui-label font-semibold text-primary">{label}</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">{pending}</p></div>)}</div></section>

        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="datos-recopilados"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">03</span><h2 className="font-headline-card text-headline-card font-semibold">Datos personales</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Los campos, datos obligatorios y condiciones de recopilación deben revisarse por formulario antes de declarar qué información se trata.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{["Formularios de contacto", "Solicitudes comerciales", "Libro de reclamaciones"].map((label) => <div className={item} key={label}><span aria-hidden="true" className="material-symbols-outlined text-[20px] text-primary">description</span><h3 className="mt-2 font-button-text text-button-text font-semibold">{label}</h3><p className="mt-1 font-ui-label text-ui-label text-text-secondary">Campos y tratamiento pendientes.</p><div className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Categorías de datos por revisar</div></div>)}</div><div className="mt-3 rounded-lg bg-surface-container-low p-4"><h3 className="font-button-text text-button-text font-semibold">Alcance por confirmar</h3><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">Tipos de datos, campos requeridos, datos sensibles y condiciones de recopilación deben revisarse individualmente antes de habilitar cada flujo.</p></div></section>

        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="finalidades"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">04</span><h2 className="font-headline-card text-headline-card font-semibold">Finalidades del tratamiento</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Cada finalidad y base jurídica debe definirse de acuerdo con los servicios que estén conectados en el sitio.</p><div className="mt-4 overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[480px] border-collapse text-left"><thead className="bg-surface-container-low font-ui-label text-ui-label text-text-secondary"><tr><th scope="col" className="px-4 py-3">Actividad</th><th scope="col" className="px-4 py-3">Finalidad informada</th><th scope="col" className="px-4 py-3">Estado</th></tr></thead><tbody className="divide-y divide-border font-body-compact text-body-compact"><tr><td className="px-4 py-3">Formulario de contacto</td><td className="px-4 py-3">Pendiente de aprobación</td><td className="px-4 py-3">Por validar</td></tr><tr><td className="px-4 py-3">Solicitud de cotización</td><td className="px-4 py-3">Pendiente de aprobación</td><td className="px-4 py-3">Por validar</td></tr><tr><td className="px-4 py-3">Reclamaciones</td><td className="px-4 py-3">Pendiente de aprobación</td><td className="px-4 py-3">Por validar</td></tr><tr><td className="px-4 py-3">Cuenta y sesión</td><td className="px-4 py-3">Pendiente de aprobación</td><td className="px-4 py-3">Por validar</td></tr><tr><td className="px-4 py-3">Preferencias del sitio</td><td className="px-4 py-3">Pendiente de aprobación</td><td className="px-4 py-3">Por validar</td></tr></tbody></table></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{["Recopilación", "Uso", "Base jurídica"].map((label) => <div key={label} className="rounded-lg border border-border bg-surface-container-low p-4"><p className="font-ui-label text-ui-label font-semibold text-primary">{label}</p><p className="mt-2 font-body-compact text-body-compact text-text-secondary">{pending}</p></div>)}</div></section>

        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="transferencia"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">05</span><h2 className="font-headline-card text-headline-card font-semibold">Transferencia y acceso a datos</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Destinatarios, encargados y transferencias —si aplican— deben verificarse antes de describirse aquí.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className={item}><h3 className="font-button-text text-button-text font-semibold">Proveedores de servicio</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Identificación y alcance pendientes.</p><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Terceros y responsables por verificar</p></div><div className={item}><h3 className="font-button-text text-button-text font-semibold">Flujos de información</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Pendiente de revisión técnica y legal.</p><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Transferencias y accesos por documentar</p></div></div><div className="mt-3 rounded-lg bg-surface-container-low p-4"><p className="font-button-text text-button-text font-semibold">Estado de revisión</p><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Destinatarios, ubicación de datos y condiciones de acceso deben validarse antes de publicar.</p></div></section>

        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="conservacion"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">06</span><h2 className="font-headline-card text-headline-card font-semibold">Plazo de conservación</h2></div><div className="mt-4 rounded-lg border border-border bg-surface-container-low p-4"><p className="font-body-compact text-body-compact leading-relaxed text-text-secondary">Los periodos de conservación, criterios de archivo y eliminación requieren definición y aprobación.</p><span className="mt-3 inline-flex rounded bg-surface px-3 py-1 font-ui-label text-ui-label font-semibold text-primary">Plazos pendientes de validación</span></div><div className="mt-3 grid gap-3 sm:grid-cols-3">{["Solicitud activa", "Relación finalizada", "Eliminación o anonimización"].map((label) => <div key={label} className="rounded-lg border border-border bg-surface-container-low p-4"><h3 className="font-ui-label text-ui-label font-semibold text-primary">{label}</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Criterio pendiente de definir.</p></div>)}</div></section>

        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="derechos-arco"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">07</span><h2 className="font-headline-card text-headline-card font-semibold">Derechos de las personas</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Los derechos aplicables y el canal para ejercerlos se describirán cuando el responsable y el procedimiento estén confirmados.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{["Canal de solicitud", "Proceso de atención", "Plazos aplicables"].map((label) => <div key={label} className={item}><span aria-hidden="true" className="material-symbols-outlined text-primary">pending_actions</span><h3 className="mt-2 font-button-text text-button-text font-semibold">{label}</h3><p className="mt-1 font-ui-label text-ui-label text-text-secondary">Pendiente.</p></div>)}</div><div className="mt-3 rounded-lg bg-surface-container-low p-4"><h3 className="font-button-text text-button-text font-semibold">Secuencia de atención por definir</h3><div className="mt-3 grid gap-3 sm:grid-cols-3">{["Recepción", "Evaluación", "Respuesta"].map((label, index) => <div key={label} className="rounded-lg border border-border bg-surface p-3"><span className="font-ui-label text-ui-label font-bold text-primary">0{index + 1}</span><p className="mt-1 font-body-compact text-body-compact font-semibold">{label}</p><p className="mt-1 font-ui-label text-ui-label text-text-muted">Pendiente de aprobación</p></div>)}</div></div></section>

        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="seguridad"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">08</span><h2 className="font-headline-card text-headline-card font-semibold">Seguridad y confidencialidad</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Las medidas que se comuniquen deben corresponder a controles implementados y comprobables.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className={item}><h3 className="font-button-text text-button-text font-semibold">Medidas técnicas</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Por documentar y validar.</p><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Controles vigentes por confirmar</p></div><div className={item}><h3 className="font-button-text text-button-text font-semibold">Medidas organizativas</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Por documentar y validar.</p><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Procedimientos por confirmar</p></div></div><div className="mt-3 rounded-lg bg-surface-container-low p-4"><p className="font-ui-label text-ui-label font-semibold text-primary">Revisión de seguridad</p><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Las salvaguardas, responsables y pasos de gestión de incidentes se publicarán tras su verificación.</p></div></section>

        <section className="scroll-mt-28 space-y-4 border-t border-border pt-8 first:border-t-0 first:pt-0" id="modificaciones"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-primary font-ui-label text-ui-label font-bold text-on-primary">09</span><h2 className="font-headline-card text-headline-card font-semibold">Actualizaciones de la política</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">La fecha, versión y condiciones de cambio se indicarán una vez aprobada la política.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-surface-container-low p-4"><span className="font-ui-label text-ui-label text-text-muted">EDICIÓN</span><p className="mt-2 font-button-text text-button-text font-semibold">Pendiente</p></div><div className="rounded-lg bg-surface-container-low p-4"><span className="font-ui-label text-ui-label text-text-muted">FECHA DE VIGENCIA</span><p className="mt-2 font-button-text text-button-text font-semibold">Por confirmar</p></div></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-surface-container-low p-4"><span className="font-button-text text-button-text font-semibold">Estado editorial</span><span className="rounded bg-surface px-3 py-1 font-ui-label text-ui-label font-semibold text-primary">Pendiente de aprobación</span></div></section>

        <section className="rounded-xl bg-primary p-5 text-on-primary sm:p-6"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-wider">Contenido institucional</p><h2 className="mt-1 font-headline-card text-headline-card font-semibold">Aviso pendiente de aprobación</h2><p className="mt-2 max-w-2xl font-body-compact text-body-compact leading-relaxed">La identidad legal, las prácticas de datos, los derechos y los canales se completarán al finalizar la revisión.</p><Link href="/cookies" className="mt-4 inline-flex min-h-10 items-center rounded-lg bg-surface px-4 font-button-text text-button-text font-semibold text-primary">Ver información de cookies</Link></section>
      </article></div></section>
    </main>
  );
}
