import Link from "next/link";
import { ContentScrollProgress } from "@/shared/ui/content-scroll-progress";
import { W20Toc } from "./islands/w20-toc";

const card = "rounded-lg border border-border bg-surface p-4";

export function ScreenW20() {
  return (
    <main className="min-h-screen bg-background pt-[76px] text-on-surface">
      <div className="sticky top-[76px] z-30 h-1 bg-surface-container"><ContentScrollProgress id="scrollProgressBar" className="h-full bg-primary-container transition-all duration-150 motion-reduce:transition-none" minPercent={0} initialWidth="0%" updateOnMount={false} /></div>
      <div className="mx-auto w-full max-w-[1200px] space-y-8 px-5 py-8 sm:px-6 lg:px-8 lg:py-10">
        <nav aria-label="Migas de pan" className="flex flex-wrap items-center gap-2 font-ui-label text-ui-label text-text-muted"><Link href="/" className="hover:text-primary">Inicio</Link><span aria-hidden="true">/</span><span>Marco institucional</span><span aria-hidden="true">/</span><span aria-current="page" className="text-on-surface">Cookies</span></nav>
        <header className="border-b border-border pb-6"><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-surface-container px-2.5 py-1 font-ui-label text-ui-label font-semibold text-primary">Información basada en la implementación</span><span className="rounded bg-surface px-2.5 py-1 font-ui-label text-ui-label text-text-muted">Validación legal pendiente</span></div><h1 className="mt-3 font-headline-hero text-headline-section font-semibold tracking-tight text-on-surface lg:text-headline-hero">Política de cookies y tecnologías de almacenamiento</h1><p className="mt-3 max-w-3xl font-body-default text-body-default leading-relaxed text-text-secondary">Resumen técnico de las cookies identificadas en el sitio. El contenido legal final, las finalidades y los servicios externos deben revisarse antes de publicar una política oficial.</p></header>

        <section aria-label="Estado de publicación" className="grid gap-3 border-b border-border pb-4 sm:grid-cols-3"><div className="flex items-center gap-2 font-ui-label text-ui-label text-text-secondary"><span aria-hidden="true" className="material-symbols-outlined text-[16px] text-primary">event</span><span>Vigencia legal: pendiente</span></div><div className="flex items-center gap-2 font-ui-label text-ui-label text-text-secondary"><span aria-hidden="true" className="material-symbols-outlined text-[16px] text-primary">layers</span><span>Versión del inventario: por revisar</span></div><div className="flex items-center gap-2 font-ui-label text-ui-label text-text-secondary"><span aria-hidden="true" className="material-symbols-outlined text-[16px] text-primary">shield</span><span>Revisión legal y técnica: pendiente</span></div></section>
        <section aria-labelledby="consent-heading" className="rounded-xl border border-border bg-surface p-5 shadow-sm sm:p-7"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="font-ui-label text-ui-label font-semibold uppercase tracking-wider text-primary">Preferencias y almacenamiento</p><h2 id="consent-heading" className="mt-1 font-headline-card text-headline-card font-semibold">Estado actual de cookies</h2><p className="mt-2 max-w-2xl font-body-compact text-body-compact leading-relaxed text-text-secondary">No se han conectado categorías opcionales de análisis o personalización al sistema del sitio.</p></div><span className="inline-flex items-center gap-2 rounded-lg border border-border bg-surface-container-low px-3 py-2 font-ui-label text-ui-label font-semibold text-text-secondary"><span aria-hidden="true" className="size-2 rounded-full bg-outline" />Sin categorías opcionales activas</span></div>
          <div className="mt-5 grid gap-5 lg:grid-cols-3">
            <article className="flex flex-col justify-between space-y-4 rounded-lg border border-border bg-surface-container-low p-5"><div className="space-y-2.5"><div className="flex items-center justify-between gap-2"><span className="font-ui-label text-ui-label font-bold uppercase tracking-wider text-primary">Categoría necesaria</span><span className="rounded bg-surface px-2 py-1 font-ui-label text-ui-label font-bold">Estado técnico</span></div><h3 className="font-button-text text-button-text font-semibold">Preferencia y sesión</h3><p className="font-body-compact text-body-compact leading-relaxed text-text-secondary">La implementación revisada incluye almacenamiento de consentimiento y una cookie de sesión cuando se inicia sesión. El inventario debe confirmarse en producción.</p></div><div className="flex items-center justify-between border-t border-border pt-3"><span className="font-ui-label text-ui-label text-text-muted">Opciones necesarias</span><span aria-label="Categoría necesaria; control deshabilitado" className="rounded bg-surface px-2 py-1 font-ui-label text-ui-label font-semibold text-primary">Según función</span></div></article>
            <article className="flex flex-col justify-between space-y-4 rounded-lg border border-border bg-surface-container-low p-5"><div className="space-y-2.5"><div className="flex items-center justify-between gap-2"><span className="font-ui-label text-ui-label font-bold uppercase tracking-wider text-text-muted">Rendimiento y métricas</span><input aria-label="Rendimiento y métricas, pendiente de validación" type="checkbox" disabled className="size-5 accent-primary" /></div><h3 className="font-button-text text-button-text font-semibold">Medición técnica</h3><p className="font-body-compact text-body-compact leading-relaxed text-text-secondary">No hay una categoría de analítica conectada al panel de consentimiento revisado.</p></div><div className="flex items-center justify-between border-t border-border pt-3"><span className="font-ui-label text-ui-label text-text-muted">Identificadores</span><span className="font-ui-label text-ui-label text-text-secondary">No configurados</span></div></article>
            <article className="flex flex-col justify-between space-y-4 rounded-lg border border-border bg-surface-container-low p-5"><div className="space-y-2.5"><div className="flex items-center justify-between gap-2"><span className="font-ui-label text-ui-label font-bold uppercase tracking-wider text-text-muted">Personalización</span><input aria-label="Personalización, pendiente de validación" type="checkbox" disabled className="size-5 accent-primary" /></div><h3 className="font-button-text text-button-text font-semibold">Preferencias de consulta</h3><p className="font-body-compact text-body-compact leading-relaxed text-text-secondary">No se ha conectado almacenamiento de filtros o preferencias técnicas de consulta.</p></div><div className="flex items-center justify-between border-t border-border pt-3"><span className="font-ui-label text-ui-label text-text-muted">Identificadores</span><span className="font-ui-label text-ui-label text-text-secondary">No configurados</span></div></article>
          </div>
          <div className="flex flex-col items-start justify-between gap-4 border-t border-border pt-4 sm:flex-row sm:items-center"><p className="flex items-start gap-2 font-body-compact text-body-compact leading-relaxed text-text-secondary"><span aria-hidden="true" className="material-symbols-outlined text-[18px] text-primary">info</span><span>La selección y el guardado de preferencias no están disponibles hasta que se conecte la gestión de consentimiento.</span></p><div className="flex w-full flex-col gap-3 sm:w-auto sm:flex-row"><button type="button" disabled className="min-h-11 cursor-not-allowed rounded-lg border border-border px-5 font-button-text text-button-text text-text-muted opacity-70">Solo necesarias</button><button type="button" disabled className="min-h-11 cursor-not-allowed rounded-lg bg-primary px-6 font-button-text text-button-text font-semibold text-on-primary opacity-60">Guardar preferencias</button></div></div>
        </section>

        <div className="grid items-start gap-6 lg:grid-cols-12 lg:gap-8"><aside className="space-y-4 lg:sticky lg:top-28 lg:col-span-4"><div className="rounded-xl border border-border bg-surface p-5"><div className="mb-4 flex items-center gap-2"><span aria-hidden="true" className="material-symbols-outlined text-[20px] text-primary">format_list_bulleted</span><h2 className="font-button-text text-button-text font-semibold">Índice</h2></div><W20Toc /></div><div className="rounded-xl border border-border bg-surface-container-low p-5"><p className="font-ui-label text-ui-label font-semibold uppercase tracking-wide text-primary">Estado del documento</p><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">Inventario técnico y política legal pendiente de revisión.</p></div></aside>

        <article className="rounded-xl bg-surface p-6 shadow-sm space-y-6 sm:p-10 lg:col-span-8">
          <section id="section-1" className="scroll-mt-28 space-y-4 border-t border-border pt-6 first:border-t-0 first:pt-0"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded bg-secondary-fixed font-ui-label text-ui-label font-bold text-primary">01</span><h2 className="font-headline-card text-headline-card font-semibold">Qué son las cookies</h2></div><div className="mt-4 space-y-3 font-body-compact text-body-compact leading-relaxed text-text-secondary"><p>Son datos que un sitio puede guardar en el navegador para conservar una preferencia o una sesión.</p><p>En el código revisado se identifican una cookie propia para guardar el consentimiento y una cookie de autenticación usada cuando una persona inicia sesión. Las funciones de analítica o personalización descritas en el diseño original no están conectadas al consentimiento.</p></div><div className="mt-4 rounded-lg bg-surface-container-low p-4"><p className="font-ui-label text-ui-label font-semibold text-primary">Alcance del inventario</p><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">Este es un resumen técnico de los módulos de consentimiento y autenticación. Debe completarse con una revisión de todos los recursos que se cargan en producción antes de publicarlo como inventario legal.</p></div></section>

          <section id="section-2" className="scroll-mt-28 space-y-4 border-t border-border pt-6 first:border-t-0 first:pt-0"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded bg-secondary-fixed font-ui-label text-ui-label font-bold text-primary">02</span><h2 className="font-headline-card text-headline-card font-semibold">Clasificación técnica</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><article className={card}><div className="flex items-center gap-2"><span aria-hidden="true" className="material-symbols-outlined text-[18px] text-primary">lock</span><h3 className="font-button-text text-button-text font-semibold">Cookies propias</h3></div><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">Los registros identificados se configuran en la aplicación: preferencia de consentimiento y sesión autenticada.</p><ul className="mt-3 space-y-2 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted"><li>Uso descrito en los módulos del sitio</li><li>Configuración documentada en el código</li><li>Revisión legal pendiente</li></ul></article><article className={card}><div className="flex items-center gap-2"><span aria-hidden="true" className="material-symbols-outlined text-[18px] text-primary">language</span><h3 className="font-button-text text-button-text font-semibold">Servicios externos</h3></div><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">No se identificaron cookies de terceros en las funciones de consentimiento revisadas. Se requiere una auditoría de recursos de producción antes de confirmarlo.</p><ul className="mt-3 space-y-2 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted"><li>Proveedores externos: por verificar</li><li>Finalidades: por verificar</li><li>Transferencias: por verificar</li></ul></article></div></section>

          <section id="section-3" className="scroll-mt-28 space-y-4 border-t border-border pt-6 first:border-t-0 first:pt-0"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded bg-secondary-fixed font-ui-label text-ui-label font-bold text-primary">03</span><h2 className="font-headline-card text-headline-card font-semibold">Inventario identificado</h2></div><span className="rounded bg-surface-container px-2.5 py-1 font-ui-label text-ui-label text-text-muted">Revisión de código</span></div><div className="mt-4 overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[540px] border-collapse text-left"><thead className="bg-surface-container-low font-ui-label text-ui-label text-text-secondary"><tr><th scope="col" className="px-4 py-3">Identificador</th><th scope="col" className="px-4 py-3">Función técnica</th><th scope="col" className="px-4 py-3">Duración configurada</th><th scope="col" className="px-4 py-3">Estado</th></tr></thead><tbody className="divide-y divide-border font-body-compact text-body-compact"><tr><td className="px-4 py-3 font-mono text-[13px]">fundigsac-consent</td><td className="px-4 py-3">Preferencia local de consentimiento</td><td className="px-4 py-3">Hasta 180 días</td><td className="px-4 py-3">Propia</td></tr><tr><td className="px-4 py-3 font-mono text-[13px]">fundigsac.session_token</td><td className="px-4 py-3">Sesión de autenticación</td><td className="px-4 py-3">7 días</td><td className="px-4 py-3">HttpOnly · SameSite=Lax</td></tr><tr><td className="px-4 py-3">Analítica</td><td className="px-4 py-3">No identificada en el módulo revisado</td><td className="px-4 py-3">No aplica</td><td className="px-4 py-3">No conectada</td></tr><tr><td className="px-4 py-3">Personalización</td><td className="px-4 py-3">No identificada en el módulo revisado</td><td className="px-4 py-3">No aplica</td><td className="px-4 py-3">No conectada</td></tr><tr><td className="px-4 py-3">Terceros</td><td className="px-4 py-3">Pendiente de auditoría de producción</td><td className="px-4 py-3">Por confirmar</td><td className="px-4 py-3">Por revisar</td></tr></tbody></table></div><p className="mt-3 font-ui-label text-ui-label leading-relaxed text-text-muted">En HTTPS, la configuración segura añade el prefijo `__Secure-` al identificador de sesión.</p><div className="mt-4 rounded-lg bg-surface-container-low p-4"><p className="font-ui-label text-ui-label font-semibold text-primary">Identificadores pendientes de verificación</p><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">La salida del navegador en producción y los proveedores externos deben revisarse para completar este inventario.</p></div></section>

          <section id="section-4" className="scroll-mt-28 space-y-4 border-t border-border pt-6 first:border-t-0 first:pt-0"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded bg-secondary-fixed font-ui-label text-ui-label font-bold text-primary">04</span><h2 className="font-headline-card text-headline-card font-semibold">Duración y almacenamiento</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className={card}><span className="material-symbols-outlined text-primary" aria-hidden="true">schedule</span><h3 className="mt-2 font-button-text text-button-text font-semibold">Preferencia local</h3><p className="mt-1 font-body-compact text-body-compact text-text-secondary">Máximo configurado de 180 días.</p></div><div className={card}><span className="material-symbols-outlined text-primary" aria-hidden="true">lock</span><h3 className="mt-2 font-button-text text-button-text font-semibold">Sesión autenticada</h3><p className="mt-1 font-body-compact text-body-compact text-text-secondary">Expiración configurada a siete días.</p></div></div><p className="mt-4 font-ui-label text-ui-label text-text-muted">La limpieza y el almacenamiento local pueden gestionarse desde la configuración del navegador.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{["Preferencia de consentimiento", "Sesión autenticada", "Datos de sitios guardados"].map((label) => <div key={label} className={card}><h3 className="font-button-text text-button-text font-semibold">{label}</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">La duración o el efecto al borrar datos depende de la configuración descrita para cada cookie.</p></div>)}</div></section>

          <section id="section-5" className="scroll-mt-28 space-y-4 border-t border-border pt-6 first:border-t-0 first:pt-0"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded bg-secondary-fixed font-ui-label text-ui-label font-bold text-primary">05</span><h2 className="font-headline-card text-headline-card font-semibold">Control desde el navegador</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Las opciones para revisar, bloquear o borrar cookies dependen de la configuración del navegador instalado.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{["Chrome y otros navegadores basados en Chromium", "Safari", "Firefox", "Microsoft Edge"].map((browser) => <div key={browser} className={card}><h3 className="font-button-text text-button-text font-semibold">{browser}</h3><p className="mt-1 font-body-compact text-body-compact text-text-secondary">Consulta la sección de privacidad y almacenamiento en la configuración del navegador.</p></div>)}</div></section>

          <section id="section-6" className="scroll-mt-28 space-y-4 border-t border-border pt-6 first:border-t-0 first:pt-0"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded bg-secondary-fixed font-ui-label text-ui-label font-bold text-primary">06</span><h2 className="font-headline-card text-headline-card font-semibold">Revisión y contacto</h2></div><p className="mt-4 font-body-compact text-body-compact leading-relaxed text-text-secondary">Responsable de privacidad, canal de contacto, fecha y versión del documento: pendientes de validación.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className={card}><h3 className="font-button-text text-button-text font-semibold">Canal de privacidad</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">Pendiente de confirmar con FUNDIGSAC.</p><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Sin correo ni teléfono publicado</p></div><div className={card}><h3 className="font-button-text text-button-text font-semibold">Revisión del inventario</h3><p className="mt-2 font-body-compact text-body-compact text-text-secondary">La lista final debe revisarse con los recursos activos en producción.</p><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">Fecha de revisión pendiente</p></div></div><div className="mt-4 rounded-lg bg-surface-container-low p-4"><p className="font-button-text text-button-text font-semibold">Documentos institucionales relacionados</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><Link href="/privacidad" className="rounded-lg border border-border bg-surface p-4 font-ui-label text-ui-label font-semibold text-primary"><span className="material-symbols-outlined block text-[20px]">policy</span><span className="mt-2 block">Aviso de privacidad</span><span className="mt-1 block font-normal text-text-secondary">Pendiente de aprobación</span></Link><Link href="/reclamaciones" className="rounded-lg border border-border bg-surface p-4 font-ui-label text-ui-label font-semibold text-primary"><span className="material-symbols-outlined block text-[20px]">assignment</span><span className="mt-2 block">Libro de reclamaciones</span><span className="mt-1 block font-normal text-text-secondary">Canal en revisión</span></Link><div className="rounded-lg border border-border bg-surface p-4 font-ui-label text-ui-label font-semibold text-primary"><span className="material-symbols-outlined block text-[20px]">cookie</span><span className="mt-2 block">Inventario de cookies</span><span className="mt-1 block font-normal text-text-secondary">Información de esta página</span></div></div></div></section>
        </article></div>
      </div>
    </main>
  );
}
