import Link from "next/link";

const families = [
  { title: "Válvulas", description: "Familia de producto", href: "/productos/valvulas", icon: "valve" },
  { title: "Tuberías", description: "Familia de producto", href: "/productos/tuberias", icon: "water" },
  { title: "Marcos y tapas", description: "Familia de producto", href: "/productos/marcos-y-tapas", icon: "grid_view" },
] as const;

export function ScreenW21() {
  return (
    <main className="min-h-screen bg-background pt-[76px] text-on-surface">
      <section className="relative overflow-hidden px-5 py-12 sm:py-16 lg:py-20">
        <div aria-hidden="true" className="pointer-events-none absolute -top-32 left-1/2 h-[380px] w-[720px] -translate-x-1/2 rounded-full bg-primary-fixed-dim/20 blur-[100px]" />
        <div className="relative mx-auto flex max-w-[1200px] flex-col items-center text-center">
          <p className="mb-5 inline-flex items-center gap-2 rounded-lg bg-surface-container px-3.5 py-1.5 font-ui-label text-ui-label font-semibold uppercase tracking-wider text-primary shadow-sm"><span aria-hidden="true" className="size-2 rounded-full bg-danger" />ERROR 404 · RUTA NO ENCONTRADA <span className="text-text-muted">|</span><span className="font-normal text-text-muted">HTTP_STATUS_NOT_FOUND</span></p>
          <div className="relative select-none"><span aria-hidden="true" className="font-headline-hero text-[112px] font-bold leading-none tracking-tighter text-primary-container/20 sm:text-[156px] lg:text-[180px]">404</span><span className="absolute inset-0 flex items-center justify-center"><span className="rounded-lg bg-surface-elevated/90 px-5 py-2 font-ui-label text-ui-label font-semibold uppercase tracking-widest text-text-secondary shadow-sm">Código no encontrado</span></span></div>
          <h1 className="mt-5 max-w-[800px] font-headline-section text-headline-section font-semibold tracking-tight text-on-surface">La página que buscas no está disponible</h1>
          <p className="mt-4 max-w-[680px] font-body-default text-body-default leading-relaxed text-text-secondary">Comprueba la dirección o busca una de las familias disponibles en el catálogo.</p>

          <form action="/buscar" method="get" role="search" className="mt-8 flex w-full max-w-[640px] flex-col gap-2 rounded-xl border border-border bg-surface p-2 shadow-sm sm:flex-row">
            <label className="sr-only" htmlFor="not-found-query">Buscar por familia</label><input className="min-h-11 min-w-0 flex-1 rounded-lg bg-surface-container-lowest px-4 font-body-default text-body-compact text-on-surface placeholder:text-text-muted focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus" id="not-found-query" name="q" type="search" placeholder="Buscar válvulas, tuberías, marcos o tapas" /><button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-5 font-button-text text-button-text text-on-primary shadow-sm hover:bg-primary-container hover:text-brand-on focus-visible:outline-2 focus-visible:outline-focus" type="submit">Buscar <span aria-hidden="true">→</span></button>
          </form>
          <div className="mt-4 flex w-full max-w-[640px] flex-wrap items-center justify-center gap-2 font-ui-label text-ui-label text-text-muted"><span className="mr-1">Explora por familia:</span>{families.map((family) => <Link key={family.href} href={family.href} className="rounded-full border border-border bg-surface px-3 py-1.5 font-semibold text-primary transition-colors hover:bg-surface-container focus-visible:outline-2 focus-visible:outline-focus">{family.title}</Link>)}</div>
          <div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-6 font-button-text text-button-text font-semibold text-on-primary shadow-sm hover:bg-primary-container hover:text-brand-on focus-visible:outline-2 focus-visible:outline-focus"><span aria-hidden="true" className="material-symbols-outlined text-[18px]">home</span>Volver al inicio</Link><Link href="/productos" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-surface-container px-5 font-button-text text-button-text font-semibold text-on-surface hover:bg-surface-container-high focus-visible:outline-2 focus-visible:outline-focus"><span aria-hidden="true" className="material-symbols-outlined text-[18px]">menu_book</span>Explorar catálogo</Link><Link href="/recursos" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-surface px-5 font-button-text text-button-text font-semibold text-primary hover:bg-surface-container-low focus-visible:outline-2 focus-visible:outline-focus"><span aria-hidden="true" className="material-symbols-outlined text-[18px]">description</span>Buscar documentación</Link></div>

          <div className="mt-14 w-full pt-4 sm:mt-16"><div className="mb-6 flex items-center justify-center gap-3"><span aria-hidden="true" className="h-px w-12 bg-outline-variant" /><h2 className="font-ui-label text-ui-label font-semibold uppercase tracking-widest text-text-muted">Familias disponibles</h2><span aria-hidden="true" className="h-px w-12 bg-outline-variant" /></div><div className="mx-auto grid max-w-[1040px] gap-5 text-left md:grid-cols-3">{families.map((family) => <Link key={family.href} href={family.href} className="group flex min-h-36 flex-col justify-between rounded-xl border border-border bg-surface p-5 shadow-sm transition-colors hover:bg-surface-container-low focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus"><div className="flex items-center justify-between"><span aria-hidden="true" className="flex size-10 items-center justify-center rounded-lg bg-surface-container text-[22px] text-primary transition-colors group-hover:bg-primary group-hover:text-on-primary">{family.icon}</span><span className="font-ui-label text-ui-label text-text-muted">{family.description}</span></div><div className="mt-4 flex items-center justify-between"><h3 className="font-headline-card text-headline-card font-semibold text-on-surface">{family.title}</h3><span aria-hidden="true" className="text-primary transition-transform group-hover:translate-x-1">→</span></div></Link>)}</div></div>

          <div className="mt-10 w-full max-w-[800px] rounded-xl bg-surface-container-high/60 p-5 text-left shadow-sm"><div className="flex items-start gap-3"><span aria-hidden="true" className="material-symbols-outlined flex size-10 shrink-0 items-center justify-center rounded-full bg-surface text-[20px] text-primary shadow-sm">info</span><div><p className="font-button-text text-button-text font-semibold text-on-surface">¿Buscabas información de un producto?</p><p className="mt-1 font-body-compact text-body-compact text-text-secondary">Explora las familias disponibles. Fichas, especificaciones y documentos se confirman en cada sección.</p><Link href="/productos" className="mt-3 inline-flex min-h-9 items-center font-button-text text-button-text font-semibold text-primary hover:underline">Abrir catálogo <span aria-hidden="true" className="ml-1">→</span></Link></div></div></div>
        </div>
      </section>
    </main>
  );
}
