import Image from "next/image";
import Link from "next/link";

const pendingFields = ["Diámetro nominal", "Dimensiones", "Materiales", "Presión de trabajo", "Masa", "Tolerancias"];
const downloads = ["Modelo tridimensional · STEP", "Plano técnico · DWG", "Ficha técnica · PDF"];

export function ScreenW23() {
  return (
    <main className="min-h-screen bg-background pt-[76px] text-on-surface">
      <div className="mx-auto w-full max-w-[1200px] space-y-5 px-4 py-5 sm:px-6 lg:px-8">
        <nav aria-label="Migas de pan" className="overflow-x-auto whitespace-nowrap py-1 font-ui-label text-ui-label text-text-muted"><ol className="flex items-center gap-2"><li><Link href="/">Inicio</Link></li><li aria-hidden="true">/</li><li><Link href="/productos">Catálogo</Link></li><li aria-hidden="true">/</li><li><Link href="/productos/valvulas">Válvulas</Link></li><li aria-hidden="true">/</li><li><Link href="/productos/valvulas/valvula-compuerta">Ficha de producto</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="font-semibold text-on-surface">Visor 3D</li></ol></nav>

        <header className="rounded-xl border border-border bg-surface p-5 shadow-sm sm:p-6"><div className="flex flex-wrap gap-2"><span className="rounded bg-surface-container px-2.5 py-1 font-ui-label text-ui-label font-semibold text-primary">Modelo 3D pendiente de validación</span><span className="rounded bg-surface-container-low px-2.5 py-1 font-ui-label text-ui-label text-text-secondary">Imagen referencial</span><span className="rounded bg-surface-container-low px-2.5 py-1 font-ui-label text-ui-label text-text-secondary">Datos técnicos pendientes</span></div><div className="mt-4 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="font-headline-section text-headline-section font-semibold tracking-tight">Válvula de compuerta</h1><p className="mt-2 max-w-3xl font-body-compact text-body-compact leading-relaxed text-text-secondary">La composición del visor se conserva como referencia. La imagen no representa un modelo dimensional aprobado y los parámetros aún no están disponibles.</p></div><Link href="/productos/valvulas/valvula-compuerta" className="inline-flex min-h-10 items-center justify-center rounded-lg border border-border bg-surface-container-low px-4 font-button-text text-button-text font-semibold hover:text-primary focus-visible:outline-2 focus-visible:outline-focus">Volver a la ficha</Link></div></header>

        <div className="grid items-start gap-5 lg:grid-cols-12">
          <div className="space-y-4 lg:col-span-8">
            <section aria-label="Visor referencial de producto" className="overflow-hidden rounded-xl border border-border bg-surface shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><div className="flex items-center gap-2"><span aria-hidden="true" className="size-2 rounded-full bg-warning"/><span className="font-ui-label text-ui-label font-semibold text-on-surface">Visor 3D no disponible</span></div><span className="font-ui-label text-ui-label text-text-muted">Imagen referencial</span></div><div className="relative flex min-h-[340px] items-center justify-center overflow-hidden bg-surface-container-low p-5 sm:min-h-[390px] sm:p-8"><div aria-hidden="true" className="absolute inset-0 opacity-40" style={{backgroundSize:"24px 24px",backgroundImage:"linear-gradient(to right, rgba(0,66,87,.08) 1px, transparent 1px), linear-gradient(to bottom, rgba(0,66,87,.08) 1px, transparent 1px)"}}/><figure className="relative z-10 m-0 flex w-full max-w-[620px] items-center justify-center"><Image src="/images/stitch/2633b42224.jpg" alt="Imagen referencial de una válvula de compuerta; no corresponde a un modelo CAD aprobado." width={1408} height={768} sizes="(min-width: 1024px) 65vw, 100vw" className="max-h-[340px] w-full rounded-lg object-contain sm:max-h-[370px]"/><figcaption className="sr-only">Imagen referencial, sin escala ni dimensiones verificadas.</figcaption></figure><span className="absolute bottom-4 left-4 rounded bg-surface/95 px-3 py-1.5 font-ui-label text-ui-label font-semibold text-on-surface">Vista referencial · sin escala</span></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-border bg-surface px-4 py-3"><p className="font-ui-label text-ui-label text-text-muted">Los controles aparecerán cuando el modelo tenga aprobación técnica.</p><div className="flex gap-2" aria-label="Controles del visor, actualmente inactivos">{[["rotate_right","Rotar"],["zoom_in","Acercar"],["download","Descargar"]].map(([icon,label])=><button key={icon} type="button" disabled aria-label={`${label}: no disponible`} className="flex size-9 items-center justify-center rounded-lg border border-border bg-surface-container-low text-text-muted disabled:cursor-not-allowed"><span aria-hidden="true" className="material-symbols-outlined text-[18px]">{icon}</span></button>)}</div></div><div className="grid grid-cols-3 gap-px border-t border-border bg-border">{["Vista", "Corte", "Wireframe"].map((label)=><button key={label} type="button" disabled className="min-h-10 bg-surface px-2 font-ui-label text-ui-label text-text-muted disabled:cursor-not-allowed">{label}</button>)}</div></section>
            <div className="grid gap-3 sm:grid-cols-3">{[["straighten","Distancia entre caras"],["fitness_center","Masa total"],["speed","Presión de trabajo"]].map(([icon,label])=><article key={label} className="rounded-xl border border-border bg-surface p-4 shadow-sm"><span aria-hidden="true" className="material-symbols-outlined text-[20px] text-primary">{icon}</span><p className="mt-2 font-ui-label text-ui-label text-text-muted">{label}</p><p className="mt-1 font-headline-card text-headline-card font-semibold text-on-surface">Pendiente</p><p className="mt-1 font-ui-label text-ui-label text-text-muted">Dato por validar</p></article>)}</div>
          </div>

          <aside className="space-y-5 lg:col-span-4">
            <section className="overflow-hidden rounded-xl border border-border bg-surface shadow-sm"><div className="flex items-center justify-between gap-3 bg-surface-container-low px-5 py-4"><div><p className="font-ui-label text-ui-label font-semibold uppercase tracking-wide text-text-muted">Configuración paramétrica</p><h2 className="mt-1 font-headline-card text-headline-card font-semibold">Ajustes del modelo CAD</h2></div><span aria-hidden="true" className="material-symbols-outlined text-primary">tune</span></div><div className="space-y-5 p-5"><fieldset disabled className="space-y-3"><legend className="font-button-text text-button-text font-semibold">Diámetro nominal</legend><div className="grid grid-cols-3 gap-2">{[1,2,3,4,5,6].map((n)=><button key={n} type="button" disabled className="min-h-11 rounded-lg border border-border bg-surface-container-low px-2 font-ui-label text-ui-label text-text-muted">Pendiente</button>)}</div><p className="font-ui-label text-ui-label text-text-muted">Rangos por confirmar en ficha técnica aprobada.</p></fieldset><fieldset disabled className="space-y-3 border-t border-border pt-4"><legend className="font-button-text text-button-text font-semibold">Tipo de accionamiento</legend><div className="space-y-2">{["Configuración A", "Configuración B", "Otra configuración"].map((label)=><label key={label} className="flex min-h-12 items-center gap-3 rounded-lg border border-border bg-surface-container-low p-3 text-text-muted"><input type="radio" disabled name="cad-actuation"/><span className="font-body-compact text-body-compact">{label} · pendiente de validación</span></label>)}</div></fieldset><dl className="grid grid-cols-2 gap-y-3 border-t border-border pt-4 font-ui-label text-ui-label">{pendingFields.map((label)=><div key={label} className="contents"><dt className="text-text-muted">{label}</dt><dd className="text-right font-semibold text-text-secondary">Por validar</dd></div>)}</dl><Link href="/cotizar?producto=valvula-compuerta" className="flex min-h-11 items-center justify-center rounded-lg bg-primary px-4 text-center font-button-text text-button-text font-semibold text-on-primary hover:bg-primary-container hover:text-brand-on focus-visible:outline-2 focus-visible:outline-focus">Solicitar cotización</Link><p className="text-center font-ui-label text-ui-label text-text-muted">Las especificaciones se revisan para cada solicitud.</p></div></section>
            <section className="rounded-xl border border-border bg-surface p-5 shadow-sm"><div className="flex items-center gap-2"><span aria-hidden="true" className="material-symbols-outlined text-primary">download_for_offline</span><h2 className="font-button-text text-button-text font-semibold">Descargas CAD / BIM</h2></div><p className="mt-2 font-body-compact text-body-compact leading-relaxed text-text-secondary">Los archivos se habilitarán después de revisión y aprobación técnica.</p><ul className="mt-4 space-y-2">{downloads.map((label)=><li key={label} className="flex items-center justify-between gap-3 rounded-lg bg-surface-container-low p-3"><span className="font-body-compact text-body-compact text-text-secondary">{label}</span><span className="shrink-0 rounded bg-surface px-2 py-1 font-ui-label text-ui-label text-text-muted">No disponible</span></li>)}</ul><p className="mt-3 border-t border-border pt-3 font-ui-label text-ui-label text-text-muted">No hay archivos aprobados para descarga.</p></section>
          </aside>
        </div>

        <section className="flex flex-col items-start gap-4 rounded-xl bg-surface-container-low p-5 shadow-sm md:flex-row md:items-center"><span aria-hidden="true" className="material-symbols-outlined flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary text-[24px] text-on-primary">verified_user</span><div className="flex-1"><p className="font-ui-label text-ui-label font-bold uppercase tracking-wider text-on-surface">Revisión técnica pendiente</p><p className="mt-1 font-body-compact text-body-compact leading-relaxed text-text-secondary">La imagen, los datos dimensionales y la documentación deben verificarse antes de presentarse como representación oficial del producto.</p></div><span className="rounded bg-surface px-3 py-2 font-ui-label text-ui-label font-semibold text-text-muted">Publicación pendiente</span></section>
      </div>
    </main>
  );
}
