import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { categories, getProduct, products } from "@/lib/catalog";
import { ProductSelection } from "@/components/product-selection";
import { ProductCard } from "@/components/product-card";
export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getProduct(slug);return p?{title:p.name,description:p.summary,alternates:{canonical:`/productos/${p.slug}`},openGraph:{title:p.name,description:p.summary}}:{}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=getProduct(slug);if(!product)notFound();const category=categories.find(c=>c.slug===product.category);const related=products.filter(p=>p.category===product.category&&p.slug!==product.slug).slice(0,3);const jsonLd={"@context":"https://schema.org","@type":"Product",name:product.name,description:product.summary,url:`https://fundigsac.com/productos/${product.slug}`,...(product.image&&!product.imageIllustrative?{image:`https://fundigsac.com${product.image}`}:{})};
  return <main className="container inner-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/><nav className="breadcrumb" aria-label="Ruta de navegación"><Link href="/">Inicio</Link><span>/</span><Link href="/productos">Productos</Link><span>/</span><Link href={`/productos?categoria=${category?.slug}`}>{category?.name}</Link><span>/</span><span>{product.name}</span></nav>
    <div className="product-detail"><div className="product-gallery"><div className={`detail-media ${product.image?product.imageIllustrative?"illustrative-media":"":"technical-stage"}`}>{product.image?<Image src={product.image} alt={product.imageIllustrative?`Ilustración del tipo de producto: ${product.name}`:product.name} fill priority sizes="(max-width: 800px) 100vw, 55vw"/>:<div><span>{category?.name}</span><strong>{product.name}</strong><small>Fotografía técnica en preparación</small></div>}</div>{product.image&&<div className="gallery-thumbs" aria-label="Vistas disponibles"><span className="gallery-thumb is-active"><Image src={product.image} alt="Vista principal" fill sizes="72px"/></span><small>{product.imageIllustrative?"Imagen ilustrativa de la familia; no representa una medida exacta.":"Imagen de referencia del catálogo actual. Solicita una ficha técnica para confirmar medidas."}</small></div>}</div><div className="detail-info"><span className="eyebrow">{category?.name}</span><h1>{product.name}</h1><p className="lead">{product.summary}</p><ProductSelection product={product}/><p className="source-note">Confirma medidas, precio y disponibilidad al cotizar.</p></div></div>
    <nav className="detail-section-nav" aria-label="Secciones del producto"><a href="#informacion-tecnica">Especificaciones técnicas</a><a href="#descripcion">Descripción</a><a href="#relacionados">Productos relacionados</a></nav>
    <section className="detail-lower"><div id="informacion-tecnica"><h2>Especificaciones técnicas</h2>{product.specs?.length?<dl className="spec-list">{product.specs.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>:<p>La ficha técnica de esta referencia está pendiente de validación. Solicita las especificaciones antes de definir tu compra.</p>}</div><div id="descripcion"><h2>Descripción</h2><p>{product.summary}</p>{product.variants&&<><h3>Medidas del documento de referencia</h3><div className="variant-table-wrap" tabIndex={0} role="region" aria-label="Tabla de medidas, desplazable"><table className="variant-table"><thead><tr><th>Medida</th><th>Referencia</th></tr></thead><tbody>{product.variants.map(v=><tr key={v.label}><td>{v.label}</td><td>{v.sdr??"Consultar"}</td></tr>)}</tbody></table></div></>}</div></section>
    {related.length>0&&<section className="section related" id="relacionados"><div className="section-heading"><h2>Productos relacionados</h2></div><div className="product-grid">{related.map(p=><ProductCard product={p} key={p.slug}/>)}</div></section>}
  </main>}
